In [3]:
import pandas as pd

In [4]:
data = pd.read_csv('../data/Students_Performance_dataset.csv')

In [5]:
data.head()

,University Admission year,Gender,Age,H.S.C passing year,Program,Current Semester,Do you have meritorious scholarship ?,Do you use University transportation?,How many hour do you study daily?,How many times do you seat for study in a day?,...,What is you interested area?,What is your relationship status?,Are you engaged with any co-curriculum activities?,With whom you are living with?,Do you have any health issues?,What was your previous SGPA?,Do you have any physical disabilities?,What is your current CGPA?,How many Credit did you have completed?,What is your monthly family income?
0,2018,Male,24,2016,BCSE,12,Yes,No,3,2,...,Data Schince,Single,Yes,Bachelor,No,2.68,No,3.15,75,25000
1,2021,Male,22,2020,BCSE,4,Yes,Yes,3,2,...,Event management,Single,Yes,Family,No,2.68,No,3.15,36,100000
2,2020,Female,21,2019,BCSE,5,No,No,3,3,...,Software,Single,No,Bachelor,No,2.68,No,3.15,50,50000
3,2021,Male,20,2020,BCSE,4,Yes,No,1,3,...,Artificial Intelligence,Single,No,Bachelor,Yes,2.68,No,3.15,36,62488
4,2021,Male,22,2019,BCSE,4,Yes,No,3,1,...,Software,Relationship,No,Bachelor,Yes,2.68,No,3.15,36,50000

In [6]:
data.columns

Index(['University Admission year', 'Gender', 'Age', 'H.S.C passing year',
       'Program', 'Current Semester', 'Do you have meritorious scholarship ?',
       'Do you use University transportation?',
       'How many hour do you study daily?',
       'How many times do you seat for study in a day?',
       'What is your preferable learning mode?', 'Do you use smart phone?',
       'Do you have personal Computer?',
       'How many hour do you spent daily in social media?',
       'Status of your English language proficiency',
       'Average attendance on class', 'Did you ever fall in probation?',
       'Did you ever got suspension?',
       'Do you attend in teacher consultancy for any kind of academical problems?',
       'What are the skills do you have ?',
       'How many hour do you spent daily on your skill development?',
       'What is you interested area?', 'What is your relationship status?',
       'Are you engaged with any co-curriculum activities?',
       'With whom you are living with?', 'Do you have any health issues?',
       'What was your previous SGPA?',
       'Do you have any physical disabilities?', 'What is your current CGPA?',
       'How many Credit did you have completed?',
       'What is your monthly family income?'],
      dtype='str')

In [13]:
# finding numeric cols
numeric_cols = data.select_dtypes(include='number').columns
numeric_cols

Index(['University Admission year', 'Age', 'H.S.C passing year',
       'Current Semester', 'How many hour do you study daily?',
       'How many times do you seat for study in a day?',
       'How many hour do you spent daily in social media?',
       'How many hour do you spent daily on your skill development?',
       'What was your previous SGPA?', 'What is your current CGPA?',
       'How many Credit did you have completed?',
       'What is your monthly family income?'],
      dtype='str')

In [15]:
# object type variables
categorical_cols = data.select_dtypes(include='str').columns
categorical_cols

Index(['Gender', 'Program', 'Do you have meritorious scholarship ?',
       'Do you use University transportation?',
       'What is your preferable learning mode?', 'Do you use smart phone?',
       'Do you have personal Computer?',
       'Status of your English language proficiency',
       'Average attendance on class', 'Did you ever fall in probation?',
       'Did you ever got suspension?',
       'Do you attend in teacher consultancy for any kind of academical problems?',
       'What are the skills do you have ?', 'What is you interested area?',
       'What is your relationship status?',
       'Are you engaged with any co-curriculum activities?',
       'With whom you are living with?', 'Do you have any health issues?',
       'Do you have any physical disabilities?'],
      dtype='str')

In [17]:
data.describe()

,University Admission year,Age,H.S.C passing year,Current Semester,How many hour do you study daily?,How many times do you seat for study in a day?,How many hour do you spent daily in social media?,How many hour do you spent daily on your skill development?,What was your previous SGPA?,What is your current CGPA?,How many Credit did you have completed?,What is your monthly family income?
count,1194.000000,1194.000000,1194.000000,1194.000000,1194.000000,1194.000000,1194.000000,1194.000000,1194.000000,1194.000000,1194.000000,1.194000e+03
mean,2020.515075,21.343384,2019.214405,6.539363,3.131491,1.940536,3.289782,2.185092,2.683945,3.165603,71.842546,6.248812e+04
std,1.354954,1.613338,1.380960,3.809884,1.649597,0.856305,2.289547,1.296101,0.871592,0.750132,48.074338,7.617356e+04
min,2013.000000,18.000000,2012.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000e+03
25%,2020.000000,20.000000,2019.000000,3.000000,2.000000,1.000000,2.000000,1.000000,2.200000,2.900000,23.000000,3.000000e+04
50%,2021.000000,21.000000,2020.000000,7.000000,3.000000,2.000000,3.000000,2.000000,2.680000,3.210000,78.000000,5.000000e+04
75%,2022.000000,22.000000,2020.000000,10.000000,4.000000,2.000000,4.000000,3.000000,3.380000,3.670000,117.000000,7.400000e+04
max,2023.000000,27.000000,2028.000000,24.000000,13.000000,7.000000,20.000000,12.000000,4.000000,4.000000,145.000000,2.000000e+06

In [20]:
# checking for missing vals
data.isnull().sum().sum()

What are the skills do you have ?    1
dtype: int64

In [ ]:
# finding the one missing value
missing_value = data.isnull().sum()
missing_value[missing_value > 0]